#!/bin/sh

BOOTX64_EFI="result/BOOTX64.EFI"

KERNEL="result/kernel"

part1="./disk/1"
part2="./disk/2"


make clean
make bootloader
make kernel

mkdir -p "$part1/EFI/BOOT"
cp $BOOTX64_EFI "$part1/EFI/BOOT"

mkdir -p "$part2/sys/kernel"
cp $KERNEL "$part2/sys/kernel"