CC = gcc
TARGET = result/kernel
CFLAGS = -ffreestanding -nostdlib -m64 -masm=att -mno-sse -mno-mmx -mno-80387
SOURCE := $(filter-out src/boot.c,$(wildcard src/*.c))
OBJECT := $(subst src/,tmp/,$(patsubst %.c,%.o,$(SOURCE)))



all: $(TARGET)

result/kernel : $(OBJECT) tmp/load_gdt.o tmp/jmp_usr.o
	ld -Tkernel.ld -static $^ -o $@

tmp/%.o : src/%.c
	$(CC) $(CFLAGS) -c $< -o $@


tmp/jmp_usr.o : src/jmp_usr.asm
	as -c $^ -o $@

tmp/load_gdt.o : src/load_gdt.asm
	as -c $^ -o $@