#!/bin/sh

escape=1


loopback=`losetup --partscan --show --find disk.img`
mount $loopback"p1" disk/1/
mount $loopback"p2" disk/2/

while [ $escape = 1 ]
do
  read -p "Type 'u' to unmount: " keypress
  if [ $keypress = "u" ]
  then
    umount disk/1/
    umount disk/2/
    losetup -d $loopback
    escape=0
  fi
done

exit 0