#!/bin/sh

unused=`losetup -f`
escape=1

losetup --offset 1048576 --sizelimit 535822336 $unused disk.img
mkdosfs -F 32 $unused
mount $unused disk/

while [ $escape = 1 ]
do
  read -p "Type 'u' to Unmount: " keypress
  if [ $keypress = "u" ]
  then
    umount disk/
    losetup -d $unused
    escape=0
  fi
done

exit 0